config/routes.rb
Rails.application.routes.draw do
 
  get 'sessions/new'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/index'
   get 'shop' => 'static_pages#cart_test'

  root               'static_pages#home' 
  get    'home'   => 'static_pages#home'
  get    'about'  => 'static_pages#about'
  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  
  

  resources :products, only: [:index]
  resources :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

   

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    belongs_to :user
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
    has_one :cart
    attr_accessor :remember_token 
    before_save {self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }
    
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
  
    def User.new_token
      SecureRandom.urlsafe_base64
    end
  
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    def forget
      update_attribute(:remember_digest, nil)
    end
    
    def authenticated?(remember_token)
        return false if  remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  include SessionsHelper
  
  

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
    render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
   @user = User.find(params[:id])
  end 
  
  def new
    @user = User.new  
  end
  
 def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to FindMyXmasTree!"
      redirect_to @user
    else
      render 'new'
    end
 end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
     session[:user_id] = user.id
    end
    
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end
    
    def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
    end
    
    def logged_in?
      !current_user.nil?
    end
    
    def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
    end
   
    def log_out
      forget(current_user)
      session.delete(:user_id)
      @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
     image_tag(gravatar_url, alt: user.name, class: "gravatar")   
    end
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", root_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/cshop/index.html.erb
 <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "My Store", root_path %></h1>
      </div>
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
        <ul>
            <li><%= link_to "Privay Policy" , "#" %></li>
             <li><%= link_to "Contact" , "#" %></li>
              <li><%= link_to "Sitemap" , "#" %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "MyXmasTree", root_path, id: "logo"%>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",  root_path  %></li>
             <li><%= link_to "Products", products_path  %></li>
          <li><%= link_to "About",  about_path  %></li>
        <% if logged_in? %>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log-in", login_path  %></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <title>TestingApp</title>
  
  <!-- shopping cart -->
  
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
 <!-- end shopping cart -->
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
 </head>
 <body>

  <%= render 'layouts/header' %>
  
  <div class="container">
  <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

 </body>
</html>
  
  
  
  
  

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb
</p>

<p>this is the second test</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Find My Xmas Tree</h1>
    
    <h2>Coming Soon</h2>
    
    <%= link_to "Sign up!", signup_path, class: "btn btn-lg btn-primary"%>
    
</div>

app/views/static_pages/login.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
 <div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>



 <div class="container">
    <div class="row">
      
      <div class="col-xs-6 text-right">
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      </div>
    </div>
    <hr>
    <%= yield %>
  </div>